"""Public CMB likelihood facade and selectable solver entrypoints.

The package root keeps likelihood callers independent of solver subpackages,
while exposing the typed result, failure, capability, and registry contracts
needed by the NumPy reference backend and future device-specific solvers.
"""

from .cmb import (
    CMBLike,
    compute_cmb_spectrum,
    compute_cmb_spectrum_batch,
    compute_cmb_spectrum_cached,
    compute_cmb_spectrum_from_contract,
)
from .contracts import (  # noqa: F401
    CMBResult,
    CMBSolverCapabilities,
    CMBSolverProtocol,
)
from .contracts_audit import (
    CMBContractAudit,
    CMBModelDeclarationDecision,
    CMBSourceGraphAudit,
    assert_bundled_cmb_contracts,
    assert_bundled_cmb_declarations,
    assert_bundled_cmb_source_graphs,
    audit_bundled_cmb_contracts,
    audit_bundled_cmb_declarations,
    audit_bundled_cmb_source_graphs,
)
from .diagnostics import (
    BUNDLED_CMB_MODEL_FILENAMES,
    CAMB_COMPARABLE_CMB_MODEL_FILENAMES,
    CMB_CERTIFICATION_TIER,
    CMB_CORPUS_BASELINE_REQUEST,
    CMB_USMF2_BASELINE_TIERS,
    CMBCorpusBaselineRow,
    CMBModelDiagnostic,
    assess_acoustic_structure,
    assess_physical_spectrum_shape,
    assess_scalar_batch_cache_evidence,
    audit_cmb_repository_integrity,
    audit_source_history_residuals,
    build_bundled_cmb_full_matrix_report,
    build_bundled_cmb_matrix_report,
    build_cmb_certification_report,
    build_cmb_corpus_baseline_report,
    build_cmb_parity_report,
    build_final_cmb_certification_report,
    compare_cmb_spectra_to_reference,
    compare_full_cmb_observable_parity,
    declared_cmb_spectrum_names,
    discover_cmb_model_records,
    discover_cmb_plugins,
    run_bundled_cmb_corpus_baseline,
    run_bundled_cmb_diagnostics,
    run_bundled_cmb_full_matrix,
    run_bundled_cmb_matrix,
    run_cmb_model_diagnostic,
    run_final_cmb_certification,
    write_bundled_cmb_full_matrix_report,
    write_bundled_cmb_matrix_report,
    write_cmb_certification_report,
    write_cmb_corpus_baseline_report,
    write_final_cmb_certification_report,
)
from .errors import (
    CMBError,
    ConstraintViolationError,
    ContractError,
    ConvergenceError,
    EngineCapabilityError,
    ImplementationError,
    InitialPointError,
    ModelDeclarationError,
    NonFiniteEvolutionError,
    ParameterDomainError,
    UnsupportedCapabilityError,
)
from .results import CMBBatchResult
from .runtime import cache, projection  # noqa: F401
from .solvers.registry import CMB_SOLVER_REGISTRY  # noqa: F401
from .solvers.registry import available_cmb_solvers  # noqa: F401
from .solvers.registry import get_cmb_solver  # noqa: F401
from .solvers.registry import register_cmb_solver  # noqa: F401
from .solvers.registry import resolve_cmb_solver  # noqa: F401
from .solvers.registry import solver_provenance  # noqa: F401

__all__ = [
    "CMBLike",
    "CMBContractAudit",
    "CMBModelDeclarationDecision",
    "CMBSourceGraphAudit",
    "CMB_CORPUS_BASELINE_REQUEST",
    "CMB_USMF2_BASELINE_TIERS",
    "BUNDLED_CMB_MODEL_FILENAMES",
    "CAMB_COMPARABLE_CMB_MODEL_FILENAMES",
    "CMB_CERTIFICATION_TIER",
    "CMBCorpusBaselineRow",
    "CMBModelDiagnostic",
    "CMBBatchResult",
    "CMBError",
    "ConstraintViolationError",
    "ContractError",
    "ConvergenceError",
    "EngineCapabilityError",
    "ImplementationError",
    "InitialPointError",
    "NonFiniteEvolutionError",
    "ParameterDomainError",
    "ModelDeclarationError",
    "UnsupportedCapabilityError",
    "compute_cmb_spectrum",
    "compute_cmb_spectrum_batch",
    "compute_cmb_spectrum_cached",
    "compute_cmb_spectrum_from_contract",
    "assess_acoustic_structure",
    "assess_scalar_batch_cache_evidence",
    "assess_physical_spectrum_shape",
    "audit_cmb_repository_integrity",
    "audit_source_history_residuals",
    "build_bundled_cmb_full_matrix_report",
    "build_bundled_cmb_matrix_report",
    "build_cmb_corpus_baseline_report",
    "build_cmb_certification_report",
    "build_cmb_parity_report",
    "build_final_cmb_certification_report",
    "compare_cmb_spectra_to_reference",
    "compare_full_cmb_observable_parity",
    "declared_cmb_spectrum_names",
    "assert_bundled_cmb_contracts",
    "assert_bundled_cmb_declarations",
    "assert_bundled_cmb_source_graphs",
    "audit_bundled_cmb_declarations",
    "audit_bundled_cmb_contracts",
    "audit_bundled_cmb_source_graphs",
    "discover_cmb_model_records",
    "discover_cmb_plugins",
    "run_bundled_cmb_corpus_baseline",
    "run_bundled_cmb_full_matrix",
    "run_bundled_cmb_matrix",
    "run_bundled_cmb_diagnostics",
    "run_cmb_model_diagnostic",
    "run_final_cmb_certification",
    "write_bundled_cmb_full_matrix_report",
    "write_bundled_cmb_matrix_report",
    "write_cmb_certification_report",
    "write_cmb_corpus_baseline_report",
    "write_final_cmb_certification_report",
]
