# Last Updated: 2025-10-30
.ONESHELL:

.PHONY: lock
lock:
	python -m piptools compile \
	--quiet \
	--allow-unsafe \
	--strip-extras \
	--output-file requirements.lock \
	        requirements.in
	# Normalise the autogenerated header so repeated runs stay identical
	python - <<-'PY'
	from pathlib import Path
	
	lock_file = Path("requirements.lock")
	lines = lock_file.read_text().splitlines()
	python_banner = "# This file is autogenerated by pip-compile"
	target = (
	    "#    pip-compile --allow-unsafe --strip-extras --output-file="
	    "requirements.lock requirements.in"
	)
	index = next(
	    (
	        i for i, line in enumerate(lines)
	        if line.startswith("#    pip-compile ")
	    ),
	    None,
	)
	if index is not None: lines[index] = target
	
	# Stabilise the Python version banner so Python 3.11 and 3.12 runs
	# emit identical output inside CI and local environments.
	banner_index = next(
	    (
	        i
	        for i, line in enumerate(lines)
	        if line.startswith(
	            "# This file is autogenerated by pip-compile with Python"
	        )
	    ),
	    None,
	)
	if banner_index is not None: lines[banner_index] = python_banner
	lock_file.write_text("\n".join(lines) + "\n")
	PY
	sed -i '1i# Last Updated: $(shell date -I)' requirements.lock
