# Last Updated: 2025-10-30
.ONESHELL:

.PHONY: lock
lock:
	python -m piptools compile \
	--quiet \
        --allow-unsafe \
        --strip-extras \
	--output-file requirements.lock \
	        requirements.in
	# Normalise the autogenerated header so repeated runs stay identical
	python - <<-'PY'
	from pathlib import Path
	
	lock_file = Path("requirements.lock")
	lines = lock_file.read_text().splitlines()
	target = (
	    "#    pip-compile --allow-unsafe --strip-extras --output-file="
	    "requirements.lock requirements.in"
	)
	index = next(
	    (
	        i for i, line in enumerate(lines)
	        if line.startswith("#    pip-compile ")
	    ),
	    None,
	)
	if index is not None: lines[index] = target
	lock_file.write_text("\n".join(lines) + "\n")
	PY
	sed -i '1i# Last Updated: $(shell date -I)' requirements.lock

