[build-system]
requires = ["setuptools>=61", "wheel", "setuptools_scm[toml]"]
build-backend = "setuptools.build_meta"

[project]
name = "copernican-suite"
description = "Evaluate cosmological models using observational data."
dynamic = ["version"]
authors = [{name = "Copernican Developers"}]
license = {file = "LICENSE.md"}
requires-python = ">=3.11"
dependencies = [
    # Keep versions in sync with requirements.lock.
    "numpy==2.2.6",
    "scipy==1.16.1",
    "matplotlib==3.10.5",
    "pandas==2.3.2",
    "sympy==1.14.0",
    "jsonschema==4.25.1",
    "camb==1.6.2", # pin to ensure Python 3.11 wheels
    "PyYAML==6.0.2",
    "astropy==7.1.0",
    "psutil==7.0.0",
    "setuptools_scm==9.2.0",
]

[project.scripts]
copernican = "copernican:main_workflow"

[tool.setuptools]
packages = ["copernican_lib", "engines"]
py-modules = ["copernican"]
include-package-data = true

[tool.setuptools.data-files]
"licenses" = ["THIRD_PARTY_LICENSES.md", "licenses/*"]


[tool.setuptools_scm]
version_scheme = "no-guess-dev"
fallback_version = "0+unknown"
