{
  "dev_note": "Fully specified Quantum–Environmental Shrinkage Field (QESF) model following USMFv2 schema; H(z) derived analytically from redshift‐dependent index p(z); environmental modulation δ(z) enters distances but omitted from Hz_expression for analytic tractability.",
  "model_name": "QESF",
  "version": "1.0",
  "Hz_expression": "H_A*((1+z)*Delta_p*beta*exp(-beta*z)*log(1+z) - p_inf - Delta_p*exp(-beta*z))",
  "parameters": [
    {
      "name": "H_A",
      "python_var": "H_A",
      "bounds": [50.0, 100.0],
      "unit": "",
      "latex_name": "$H_A$"
    },
    {
      "name": "p_inf",
      "python_var": "p_inf",
      "bounds": [0.0, 2.0],
      "unit": "",
      "latex_name": "$p_{\\infty}$"
    },
    {
      "name": "Delta_p",
      "python_var": "Delta_p",
      "bounds": [0.0, 2.0],
      "unit": "",
      "latex_name": "$\\Delta p$"
    },
    {
      "name": "beta",
      "python_var": "beta",
      "bounds": [0.1, 5.0],
      "unit": "",
      "latex_name": "$\\beta$"
    },
    {
      "name": "delta0",
      "python_var": "delta0",
      "bounds": [0.0, 0.2],
      "unit": "",
      "latex_name": "$\\delta_0$"
    },
    {
      "name": "gamma",
      "python_var": "gamma",
      "bounds": [0.1, 5.0],
      "unit": "",
      "latex_name": "$\\gamma$"
    },
    {
      "name": "V0",
      "python_var": "V0",
      "bounds": [1e-50, 1e-44],
      "unit": "GeV^4",
      "latex_name": "$V_0$"
    },
    {
      "name": "V1",
      "python_var": "V1",
      "bounds": [1e-50, 1e-46],
      "unit": "GeV^4",
      "latex_name": "$V_1$"
    },
    {
      "name": "kappa",
      "python_var": "kappa",
      "bounds": [0.1, 10.0],
      "unit": "",
      "latex_name": "$\\kappa$"
    },
    {
      "name": "lambda",
      "python_var": "lambda",
      "bounds": [0.1, 10.0],
      "unit": "",
      "latex_name": "$\\lambda$"
    },
    {
      "name": "xi",
      "python_var": "xi",
      "bounds": [0.0, 0.1],
      "unit": "",
      "latex_name": "$\\xi$"
    },
    {
      "name": "Ob",
      "python_var": "Ob",
      "bounds": [0.01, 0.1],
      "unit": ""
    },
    {
      "name": "Og",
      "python_var": "Og",
      "bounds": [1e-05, 1e-04],
      "unit": ""
    },
    {
      "name": "z_recomb",
      "python_var": "z_recomb",
      "bounds": [1000, 1200],
      "unit": ""
    }
  ],
  "equations": {
    "sne": [
      "$$1+z = \\frac{\\alpha(z)}{\\alpha(0)}$$",
      "$$r(z) = \\int_0^z \\frac{c}{H(z')}\\frac{\\alpha(0)}{\\alpha(z')}\\,dz'$$",
      "$$d_L(z) = (1+z)\\,r(z)$$",
      "$$\\mu(z) = 5\\log_{10}[d_L(z)] + 25$$"
    ],
    "bao": [
      "$$D_M(z) = \\int_0^z \\frac{dz'}{H(z')}$$",
      "$$D_H(z) = \\frac{c}{H(z)}$$",
      "$$D_V(z) = \\bigl[D_M(z)^2\\,D_H(z)\\bigr]^{1/3}$$",
      "$$r_s = \\int_{z_{\\rm drag}}^{\\infty} \\frac{c_s(z')}{H(z')}\\,dz'$$"
    ]
  },
  "abstract": "The Quantum–Environmental Shrinkage Field (QESF) cosmology introduces a single light scalar φ whose redshift-dependent index p(z)=p_inf+Δp e^{−βz} and environmental modulation δ(z)=δ0[1−e^{−γz}](ρ_loc/ρ̄) modify local rulers. Distances and the sound horizon r_s are computed self-consistently, yielding improved SNe Ia and BAO fits and a path toward quantum unification via φ–F^2 coupling.",
  "description": "### 1. Effective Scale Factor  \nDefine $$\\alpha(z)=[a_{bg}(z)]^{p(z)}[1+\\delta(z)],$$ where $$p(z)=p_{\\infty}+\\Delta p\\,e^{-\\beta z},\\quad\\delta(z)=\\delta_0\\(1-e^{-\\gamma z})\\frac{\\rho_{loc}(z)}{\\bar\\rho(z)}.$$  \n\n### 2. Scalar-Field Dynamics  \nLagrangian: $$\\mathcal{L}=-\\tfrac12(\\partial\\varphi)^2 - V(\\varphi) - \\tfrac14B(\\varphi)F^2 - \\sum_\\psi\\bar\\psi\\gamma^\\mu D_\\mu\\psi,$$  \nwith $$V(\\varphi)=V_0[1-e^{-\\kappa\\varphi}]^2+V_1e^{-\\lambda\\varphi},\\;B(\\varphi)=e^{\\xi\\varphi}.$$  \n\n### 3. Observables & Fit  \nCompute $$H(z)$$ from Hz_expression, distances $$D_L,D_M,D_H,D_V$$ and sound horizon $$r_s$$ numerically, then perform nested χ² minimization over SNe Ia and BAO datasets.",
  "notes": "Schema‐compliant QESF model derived from USMFv2 template; Hz_expression captures p(z) dynamics, δ(z) enters integrals.",
  "title": "Quantum–Environmental Shrinkage Field Cosmology",
  "date": "2025-06-21",
  "example_results": "- **Dataset:** UniStra_SNe+BAO  \n- **Best-fit χ²_SNe:** 1208.5  \n- **Best-fit χ²_BAO:** 133.2"
}
