# Last Updated: 2025-11-05
"""Regression tests for ``tools.update_lock``."""

from __future__ import annotations

import importlib.util
import sys
from datetime import date
from pathlib import Path

SPEC = importlib.util.spec_from_file_location(
    "copernican_update_lock",
    Path(__file__).resolve().parents[1] / "tools" / "update_lock.py",
)
MODULE = importlib.util.module_from_spec(SPEC)
assert SPEC and SPEC.loader  # for static analysis tools
sys.modules.setdefault(SPEC.name, MODULE)
SPEC.loader.exec_module(MODULE)


def _write_lock(path: Path, header: str, body: list[str]) -> None:
    """Helper that materialises a lockfile with ``header`` and ``body``."""

    path.write_text("\n".join([header, *body]) + "\n", encoding="utf-8")


def _monkeypatch_compile(monkeypatch, body: list[str]) -> None:
    """Replace ``run_pip_compile`` with a deterministic writer."""

    def _fake_compile(
        root: Path, requirements_in: Path, output_path: Path
    ) -> None:
        Path(output_path).write_text("\n".join(body) + "\n", encoding="utf-8")

    monkeypatch.setattr(MODULE, "run_pip_compile", _fake_compile)


def test_update_lockfile_preserves_header_when_body_is_unchanged(
    tmp_path, monkeypatch
) -> None:
    """When the dependency body matches we keep the previous timestamp."""

    body = [
        "#",
        "# This file is autogenerated by pip-compile",
        "package==1.0.0",
    ]
    (tmp_path / "requirements.in").write_text("package\n", encoding="utf-8")
    lock = tmp_path / "requirements.lock"
    _write_lock(lock, "# Last Updated: 2025-11-04", body)
    _monkeypatch_compile(monkeypatch, body)

    changed = MODULE.update_lockfile(tmp_path, today=date(2025, 11, 5))

    assert not changed
    contents = lock.read_text(encoding="utf-8").splitlines()
    assert contents[0] == "# Last Updated: 2025-11-04"


def test_update_lockfile_advances_header_when_body_changes(
    tmp_path, monkeypatch
) -> None:
    """A new dependency body should advance the ``Last Updated`` banner."""

    original_body = [
        "#",
        "# This file is autogenerated by pip-compile",
        "package==1.0.0",
    ]
    new_body = original_body + ["second==2.0.0"]
    (tmp_path / "requirements.in").write_text("package\n", encoding="utf-8")
    lock = tmp_path / "requirements.lock"
    _write_lock(lock, "# Last Updated: 2025-11-04", original_body)
    _monkeypatch_compile(monkeypatch, new_body)

    changed = MODULE.update_lockfile(tmp_path, today=date(2025, 11, 5))

    assert changed
    contents = lock.read_text(encoding="utf-8").splitlines()
    assert contents[0] == "# Last Updated: 2025-11-05"
    assert contents[1:] == new_body


def test_update_lockfile_requires_requirements_in(tmp_path) -> None:
    """The helper should raise ``SystemExit`` when inputs are missing."""

    (tmp_path / "requirements.lock").write_text("", encoding="utf-8")

    try:
        MODULE.update_lockfile(tmp_path, today=date(2025, 11, 5))
    except SystemExit as exc:
        assert "requirements.in is missing" in str(exc)
    else:  # pragma: no cover - defensive assertion
        raise AssertionError(
            "update_lockfile did not abort without requirements.in"
        )
