"""Regression tests for ``tools.update_lock``."""

from __future__ import annotations

import importlib.util
import sys
import types
from pathlib import Path

SPEC = importlib.util.spec_from_file_location(
    "copernican_update_lock",
    Path(__file__).resolve().parents[1] / "tools" / "update_lock.py",
)
MODULE = importlib.util.module_from_spec(SPEC)
assert SPEC and SPEC.loader  # for static analysis tools
sys.modules.setdefault(SPEC.name, MODULE)
SPEC.loader.exec_module(MODULE)

def _force_missing_piptools(monkeypatch) -> None:
    """Pretend ``piptools`` is unavailable during the test."""

    def _missing_find_spec(name: str) -> types.ModuleType | None:
        del name
        return None

    monkeypatch.setattr(MODULE.importlib.util, "find_spec", _missing_find_spec)

def _write_lock(path: Path, body: list[str]) -> None:
    """Helper that materialises a lockfile body without metadata."""

    path.write_text("\n".join(body) + "\n", encoding="utf-8")

def _monkeypatch_compile(monkeypatch, body: list[str]) -> None:
    """Replace ``run_pip_compile`` with a deterministic writer."""

    def _fake_compile(
        root: Path, requirements_in: Path, output_path: Path
    ) -> None:
        Path(output_path).write_text("\n".join(body) + "\n", encoding="utf-8")

    monkeypatch.setattr(MODULE, "run_pip_compile", _fake_compile)

def test_update_lockfile_skips_rewrite_when_body_is_unchanged(
    tmp_path, monkeypatch
) -> None:
    """When the dependency body matches the lockfile should remain intact."""

    body = [
        "#",
        "# This file is autogenerated by pip-compile",
        "package==1.0.0",
    ]
    (tmp_path / "requirements.in").write_text("package\n", encoding="utf-8")
    lock = tmp_path / "requirements.lock"
    _write_lock(lock, body)
    _monkeypatch_compile(monkeypatch, body)

    changed = MODULE.update_lockfile(tmp_path)

    assert not changed
    contents = lock.read_text(encoding="utf-8").splitlines()
    assert contents == body

def test_update_lockfile_rewrites_when_body_changes(
    tmp_path, monkeypatch
) -> None:
    """A new dependency body should replace the lockfile contents."""

    original_body = [
        "#",
        "# This file is autogenerated by pip-compile",
        "package==1.0.0",
    ]
    new_body = original_body + ["second==2.0.0"]
    (tmp_path / "requirements.in").write_text("package\n", encoding="utf-8")
    lock = tmp_path / "requirements.lock"
    _write_lock(lock, original_body)
    _monkeypatch_compile(monkeypatch, new_body)

    changed = MODULE.update_lockfile(tmp_path)

    assert changed
    contents = lock.read_text(encoding="utf-8").splitlines()
    assert contents == new_body

def test_update_lockfile_requires_requirements_in(tmp_path) -> None:
    """The helper should raise ``SystemExit`` when inputs are missing."""

    (tmp_path / "requirements.lock").write_text("", encoding="utf-8")

    try:
        MODULE.update_lockfile(tmp_path)
    except SystemExit as exc:
        assert "requirements.in is missing" in str(exc)
    else:  # pragma: no cover - defensive assertion
        raise AssertionError(
            "update_lockfile did not abort without requirements.in"
        )

def test_run_pip_compile_aborts_without_piptools(
    tmp_path, monkeypatch
) -> None:
    """``run_pip_compile`` should stop early when ``piptools`` is missing."""

    _force_missing_piptools(monkeypatch)

    def _unexpected_run(*args, **kwargs):  # pragma: no cover - defensive guard
        raise AssertionError("pip-compile executed despite missing piptools")

    monkeypatch.setattr(MODULE.subprocess, "run", _unexpected_run)

    dummy_in = tmp_path / "requirements.in"
    dummy_in.write_text("", encoding="utf-8")

    try:
        MODULE.run_pip_compile(
            tmp_path, dummy_in, tmp_path / "requirements.lock"
        )
    except SystemExit as exc:
        assert "pip-tools is required" in str(exc)
    else:  # pragma: no cover - defensive assertion
        raise AssertionError("run_pip_compile did not abort without piptools")
