# Copyright (c) 2025 Copernican Suite developers.
# See LICENSE.md in the repository root for details.

"""Bridge between generated model callables and numerical engines.

Model YAML files are transformed into Python functions by
``copernican_lib.model_coder``.  Engines, however, operate on a plain
"plugin" object with a fixed set of attributes and callables.  This module
assembles that object, exposes metadata and verifies that required hooks
are present.  Dataset compatibility flags such as ``valid_for_cmb`` allow
engines to skip unsupported calculations gracefully.
"""

# Engines expect models in a specific "plugin" format. This module provides
# helper functions that take the parsed YAML representation of a model and
# turn it into a simple object with the required attributes and callables.

import ast
import inspect
import logging
import math
import operator
import re
from itertools import zip_longest
from types import SimpleNamespace
from typing import Any, Callable, Iterable, Mapping, Sequence

REQUIRED_FUNCTIONS = [
    "distance_modulus_model",
    "get_comoving_distance_Mpc",
    "get_luminosity_distance_Mpc",
    "get_angular_diameter_distance_Mpc",
    "get_Hz_per_Mpc",
    "get_DV_Mpc",
    "get_sound_horizon_rs_Mpc",
]

REQUIRED_ATTRIBUTES = [
    "MODEL_NAME",
    "MODEL_DESCRIPTION",
    "MODEL_ABSTRACT",
    "PARAMETER_NAMES",
    "PARAMETER_LATEX_NAMES",
    "PARAMETER_UNITS",
    "INITIAL_GUESSES",
    "PARAMETER_BOUNDS",
    "FIXED_PARAMS",
    "PARAMETER_PRIORS",
]

# Allowed math helpers for expression evaluation in ``get_camb_params``.
ALLOWED_MATH_FUNCS = {
    "sin": math.sin,
    "cos": math.cos,
    "tan": math.tan,
    "exp": math.exp,
    "log": math.log,
    "sqrt": math.sqrt,
}
ALLOWED_CONSTANTS = {"pi": math.pi, "e": math.e}

# Mappings from AST nodes to the corresponding Python operators. Only a small
# subset of numeric operations is supported to keep expressions predictable.
BIN_OPS = {
    ast.Add: operator.add,
    ast.Sub: operator.sub,
    ast.Mult: operator.mul,
    ast.Div: operator.truediv,
    ast.Pow: operator.pow,
}
UNARY_OPS = {ast.UAdd: operator.pos, ast.USub: operator.neg}


def build_plugin(model_data, func_dict):
    """Return an object mimicking the engine plugin interface.

    Parameters
    ----------
    model_data : dict
        Parsed YAML structure containing model metadata and parameter
        definitions.
    func_dict : dict
        Mapping of function names to callables generated by
        :mod:`model_coder`.

    Returns
    -------
    SimpleNamespace
        Object exposing attributes and distance functions expected by
        engines.
    """
    plugin = SimpleNamespace()
    params = model_data["parameters"]
    plugin.MODEL_NAME = model_data.get("model_name", "GeneratedModel")
    plugin.MODEL_DESCRIPTION = model_data.get("description", "")
    plugin.MODEL_ABSTRACT = model_data.get("abstract", "")
    plugin.PARAMETER_NAMES = [p["python_var"] for p in params]
    plugin.PARAMETER_LATEX_NAMES = [p["latex_name"] for p in params]
    plugin.PARAMETER_UNITS = [p.get("unit", "") for p in params]
    plugin.INITIAL_GUESSES = [sum(p["bounds"]) / 2.0 for p in params]
    plugin.PARAMETER_BOUNDS = [tuple(p["bounds"]) for p in params]
    plugin.FIXED_PARAMS = {}
    # Preserve prior metadata so engines can apply external constraints.
    plugin.PARAMETER_PRIORS = [p.get("prior", {}) for p in params]
    plugin.valid_for_distance_metrics = model_data.get(
        "valid_for_distance_metrics", True
    )
    plugin.valid_for_bao = model_data.get("valid_for_bao", True)
    plugin.valid_for_cmb = model_data.get("valid_for_cmb", True)
    plugin.CMB_PARAM_MAP = model_data.get("cmb", {}).get("param_map", {})
    if plugin.valid_for_cmb and not plugin.CMB_PARAM_MAP:
        logging.getLogger().warning(
            "Model marked valid_for_cmb but no cmb.param_map provided. "
            "Disabling CMB support."
        )
        plugin.valid_for_cmb = False

    def get_camb_params(values):
        """Return a CAMB parameter dictionary from ``values``.

        Expressions in ``plugin.CMB_PARAM_MAP`` may reference model parameter
        names and a limited set of math helpers. Supported functions are
        ``sin``, ``cos``, ``tan``, ``exp``, ``log`` and ``sqrt``. Only numeric
        literals, parameter names and the operators ``+``, ``-``, ``*``, ``/``
        and ``**`` are permitted. Any other identifier or construct raises a
        :class:`ValueError` to block unsafe code execution.
        """

        logger = logging.getLogger()
        env = {
            name: float(val)
            for name, val in zip(plugin.PARAMETER_NAMES, values)
        }
        replacements = dict(
            zip(
                [ln.strip("$") for ln in plugin.PARAMETER_LATEX_NAMES],
                plugin.PARAMETER_NAMES,
            )
        )

        def _eval_safe(expr: str) -> float:
            """Evaluate ``expr`` using a restricted AST interpreter.

            Parameters
            ----------
            expr : str
                Expression referencing parameter names and whitelisted math
                helpers.

            Returns
            -------
            float
                Numerical result of ``expr``.

            Raises
            ------
            ValueError
                If ``expr`` contains disallowed syntax or exceeds
                complexity limits.
            """

            try:
                node = ast.parse(expr, mode="eval")
            except SyntaxError as exc:  # pragma: no cover - SyntaxError rare
                raise ValueError(f"invalid expression '{expr}'") from exc

            # Limit expression complexity to avoid pathological evaluations.
            MAX_NODES = 100
            MAX_DEPTH = 20
            if sum(1 for _ in ast.walk(node)) > MAX_NODES:
                raise ValueError("expression too complex")

            def _eval(node: ast.AST, depth: int = 0) -> float:
                if depth > MAX_DEPTH:
                    raise ValueError("expression too complex")
                if isinstance(node, ast.Expression):
                    return _eval(node.body, depth + 1)
                if isinstance(node, ast.Constant):
                    if isinstance(node.value, (int, float)):
                        return float(node.value)
                    raise ValueError("non-numeric literal")
                if isinstance(node, ast.BinOp):
                    op = BIN_OPS.get(type(node.op))
                    if op is None:
                        raise ValueError("operator not allowed")
                    return op(
                        _eval(node.left, depth + 1),
                        _eval(node.right, depth + 1),
                    )
                if isinstance(node, ast.UnaryOp):
                    op = UNARY_OPS.get(type(node.op))
                    if op is None:
                        raise ValueError("operator not allowed")
                    return op(_eval(node.operand, depth + 1))
                if isinstance(node, ast.Name):
                    if node.id in env:
                        return env[node.id]
                    if node.id in ALLOWED_CONSTANTS:
                        return ALLOWED_CONSTANTS[node.id]
                    raise ValueError(f"name '{node.id}' not allowed")
                if isinstance(node, ast.Call):
                    if not isinstance(node.func, ast.Name):
                        raise ValueError("invalid function call")
                    func = ALLOWED_MATH_FUNCS.get(node.func.id)
                    if func is None:
                        raise ValueError(
                            f"function '{node.func.id}' not allowed"
                        )
                    if node.keywords:
                        raise ValueError("keyword arguments not supported")
                    args = [_eval(arg, depth + 1) for arg in node.args]
                    return float(func(*args))
                raise ValueError("expression not allowed")

            return _eval(node)

        camb_params = {}
        for key, expr in plugin.CMB_PARAM_MAP.items():
            if isinstance(expr, str):
                clean_expr = expr
                for latex, var in replacements.items():
                    clean_expr = clean_expr.replace(latex, var)
                try:
                    val = _eval_safe(clean_expr)
                except ValueError as exc:
                    logger.error(
                        f"(get_camb_params): failed to evaluate "
                        f"'{expr}' for '{key}': {exc}"
                    )
                    raise
            else:
                val = expr
            camb_params[key] = float(val)
        return camb_params

    plugin.get_camb_params = get_camb_params

    def sanitize_equation(eq_line: str) -> str:
        """Return a Matplotlib-friendly LaTeX string."""
        if not isinstance(eq_line, str):
            return ""
        eq = eq_line.strip()
        eq = re.sub(r"^\$+", "", eq)
        eq = re.sub(r"\$+$", "", eq)
        return f"${eq.strip()}$" if eq else ""

    eqs = model_data.get("equations", {})
    sne_eqs = eqs.get("sne", [])
    bao_eqs = eqs.get("bao", [])
    plugin.MODEL_EQUATIONS_LATEX_SN = [sanitize_equation(e) for e in sne_eqs]
    plugin.MODEL_EQUATIONS_LATEX_BAO = [sanitize_equation(e) for e in bao_eqs]
    if "filename" in model_data:
        plugin.MODEL_FILENAME = model_data["filename"]
    for name, func in func_dict.items():
        setattr(plugin, name, func)

    validate_plugin(plugin)
    return plugin


def make_logposterior(
    like: Callable[[Sequence[float]], float],
    priors: Iterable[Mapping[str, Any]] | None,
) -> Callable[[Sequence[float]], float]:
    """Return a posterior callable combining ``like`` with parameter priors.

    Parameters
    ----------
    like:
        Callable returning the natural logarithm of the likelihood for a
        *physical* parameter vector.  The callable may expose optional
        ``parameter_bounds`` and ``parameter_transforms`` attributes.  Bounds
        are interpreted as inclusive ``(lower, upper)`` pairs and are enforced
        before calling the likelihood.  Transforms allow engines to operate on
        unconstrained coordinates by mapping raw walker positions onto the
        physical domain.  Each transform callable should accept a single float
        and either return the transformed value directly or a ``(value,
        log_jacobian)`` tuple capturing the Jacobian contribution of the
        transform.  When the attribute is missing or entries are ``None`` the
        parameter is left unchanged.
    priors:
        Iterable of prior definitions mirroring the structures parsed from
        model YAML files.  Supported entries currently include ``type:
        "uniform"`` with ``lower``/``upper`` (or ``min``/``max``) edges and
        ``type: "gaussian"`` with ``mean``/``sigma``.  Unknown priors are
        ignored after emitting a warning so that future extensions remain
        backward compatible.

    Returns
    -------
    Callable[[Sequence[float]], float]
        Function mapping a parameter vector to the combined log-posterior.  The
        callable returns ``-inf`` whenever bounds or priors are violated, a
        transform fails or the underlying likelihood reports a non-finite
        value.

    Notes
    -----
    Engines call the returned function repeatedly during sampling.  Expensive
    validation is therefore avoided inside the loop—inputs are normalised once
    up front, leaving the inner evaluation to perform only the strictly
    necessary checks.  The helper leans on duck-typed attributes instead of a
    rigid protocol so that existing engines can opt-in incrementally without
    breaking the public API exposed to model plugins.
    """

    logger = logging.getLogger()

    # Normalise optional metadata once so the inner evaluation loop can remain
    # allocation-free.  ``priors`` defaults to an empty tuple so missing
    # entries behave like uninformative priors.
    priors_list = [dict(p) for p in (priors or [])]

    bounds = getattr(like, "parameter_bounds", None)
    if bounds is not None:
        bounds = [
            (
                None if low is None else float(low),
                None if high is None else float(high),
            )
            for low, high in bounds
        ]

    transforms = getattr(like, "parameter_transforms", None)
    if transforms is not None:
        transforms = list(transforms)

    def _evaluate(params: Sequence[float]) -> float:
        """Return the posterior value for ``params`` with safeguards."""

        # Convert the incoming sequence into a tuple so we can iterate multiple
        # times without re-evaluating generators supplied by callers.  Casting
        # to ``float`` eagerly keeps downstream NumPy calls predictable.
        try:
            raw_values = tuple(float(val) for val in params)
        except (TypeError, ValueError):
            logger.debug("(make_logposterior): received non-numeric params")
            return float("-inf")

        transformed: list[float] = []
        log_jacobian = 0.0

        # Apply optional per-parameter transforms.  When a transform returns a
        # ``(value, log_jacobian)`` tuple we accumulate the Jacobian term so
        # the posterior remains properly normalised in the transformed space.
        for idx, value in enumerate(raw_values):
            transform = None
            if transforms is not None and idx < len(transforms):
                transform = transforms[idx]
            if transform is None:
                transformed.append(value)
                continue
            try:
                result = transform(value)
            except Exception as exc:  # pragma: no cover - defensive logging
                logger.debug(
                    "(make_logposterior): transform %d failed: %s", idx, exc
                )
                return float("-inf")
            if isinstance(result, tuple):
                if len(result) != 2:
                    logger.debug(
                        "(make_logposterior): transform %d returned %s",
                        idx,
                        result,
                    )
                    return float("-inf")
                new_val, jac = result
            else:
                new_val, jac = result, 0.0
            try:
                transformed.append(float(new_val))
                log_jacobian += float(jac)
            except (TypeError, ValueError):
                logger.debug(
                    "(make_logposterior): transform %d produced non-float", idx
                )
                return float("-inf")

        # Enforce parameter bounds before evaluating the likelihood.  Bounds
        # are inclusive and accept ``None`` as an open limit.
        if bounds is not None:
            for idx, value in enumerate(transformed):
                try:
                    low_val, high_val = bounds[idx]
                except IndexError:
                    low_val, high_val = (None, None)
                if low_val is not None and value < low_val:
                    return float("-inf")
                if high_val is not None and value > high_val:
                    return float("-inf")

        log_prior = log_jacobian
        for idx, (value, prior) in enumerate(
            zip_longest(transformed, priors_list, fillvalue=None)
        ):
            if prior is None or not prior:
                continue
            ptype = str(prior.get("type") or prior.get("distribution"))
            if ptype.lower() == "uniform":
                lower = prior.get("lower", prior.get("min"))
                upper = prior.get("upper", prior.get("max"))
                lower = None if lower is None else float(lower)
                upper = None if upper is None else float(upper)
                if lower is not None and value < lower:
                    return float("-inf")
                if upper is not None and value > upper:
                    return float("-inf")
                if lower is not None and upper is not None and upper > lower:
                    log_prior -= math.log(upper - lower)
            elif ptype.lower() == "gaussian":
                mean = prior.get("mean")
                sigma = prior.get("sigma")
                if mean is None or sigma in (None, 0):
                    logger.debug(
                        "(make_logposterior): gaussian prior %d missing"
                        " parameters",
                        idx,
                    )
                    return float("-inf")
                sigma = float(sigma)
                if not math.isfinite(sigma) or sigma <= 0.0:
                    return float("-inf")
                mean = float(mean)
                delta = (value - mean) / sigma
                log_prior += -0.5 * delta * delta - math.log(
                    sigma * math.sqrt(2.0 * math.pi)
                )
            elif ptype:
                logger.warning(
                    "(make_logposterior): unsupported prior type '%s' ignored",
                    ptype,
                )

        log_like = like(transformed)
        if not math.isfinite(log_like):
            return float("-inf")
        return float(log_like + log_prior)

    return _evaluate


def validate_plugin(plugin):
    """Validate that ``plugin`` exposes required attributes and functions.

    Engines depend on a uniform interface so that any generated model can be
    swapped in.  This routine checks for the presence of mandatory
    attributes, verifies that required callables accept at least one
    parameter and logs descriptive errors when something is missing.  A
    boolean result indicates whether execution may continue.
    """
    # Engines rely on a consistent interface. This function checks for the
    # presence of all mandatory methods and attributes and logs helpful error
    # messages when something is missing. It returns ``True`` for a valid
    # plugin and ``False`` otherwise.
    logger = logging.getLogger()

    req_attrs = REQUIRED_ATTRIBUTES
    missing_attrs = [attr for attr in req_attrs if not hasattr(plugin, attr)]
    if missing_attrs:
        logger.error(
            f"Plugin validation failed. Missing attributes: {missing_attrs}",
        )
        return False

    required_funcs = list(REQUIRED_FUNCTIONS)
    if getattr(plugin, "valid_for_distance_metrics", True) is False:
        required_funcs = ["distance_modulus_model"]
    elif getattr(plugin, "valid_for_bao", True) is False:
        required_funcs = [
            "distance_modulus_model",
            "get_comoving_distance_Mpc",
            "get_luminosity_distance_Mpc",
            "get_angular_diameter_distance_Mpc",
            "get_Hz_per_Mpc",
            "get_DV_Mpc",
        ]
    # When the model lacks CMB support, exclude the spectrum routine from the
    # required function list.

    for fname in required_funcs:
        func = getattr(plugin, fname, None)
        if not callable(func):
            logger.error(
                f"Plugin validation failed. Missing function '{fname}'.",
            )
            return False
        try:
            sig = inspect.signature(func)
        except (TypeError, ValueError):
            logger.error(
                f"Plugin validation failed. Unable to inspect '{fname}'.",
            )
            return False
        if not sig.parameters:
            logger.error(
                "Plugin validation failed. Function '%s' has no parameters.",
                fname,
            )
            return False

    return True
