# Copyright (c) 2025 Copernican Suite developers.
# Last Updated: 2025-10-31
# See LICENSE.md in the repository root for details.

"""Translate sanitized model YAML into executable NumPy-aware callables.

Every cosmological model is stored as YAML. This module parses that file,
converts equations to SymPy expressions and then compiles them into fast
NumPy functions suitable for evaluation within the engines. Spawn-based
multiprocessing pools depend on pickling to ship these helpers to worker
processes, so the generated callables must rebuild themselves deterministically
whenever they are unpickled.
"""

import ast
import itertools
import logging
import re
import sys
from pathlib import Path

import numpy as np
import sympy as sp
import yaml
from scipy.integrate import cumulative_trapezoid, quad
from sympy.parsing.sympy_parser import (
    implicit_multiplication_application,
    parse_expr,
    standard_transformations,
)
from sympy.printing.numpy import NumPyPrinter

from . import console_output as console
from . import error_handler, latex_utils

_GENERATED_NAME_COUNTER = itertools.count(1)


class _GeneratedCallable:
    """Wrap a SymPy expression inside a self-reconstructing callable.

    The engines expect regular callables, yet plain functions generated by
    :func:`sympy.lambdify` cannot be pickled safely because they are defined
    dynamically inside helper modules that only exist in the parent process.
    ``_GeneratedCallable`` captures the SymPy representation plus argument
    metadata so ``__setstate__`` can rebuild the helper inside any worker that
    receives it through ``multiprocessing``'s ``spawn`` mechanism.
    """

    __slots__ = ("_state", "_callable")

    def __init__(
        self, *, expr_repr, arg_names, has_integral, name_hint, sym_expr=None
    ):
        self._state = {
            "expr_repr": expr_repr,
            "arg_names": tuple(arg_names),
            "has_integral": bool(has_integral),
            "name_hint": name_hint,
        }
        self._callable = self._build_callable(sym_expr=sym_expr)

    @property
    def python_function(self):
        """Return the underlying Python function for diagnostics.

        Engines should treat the wrapper as the canonical callable, yet tests
        and debugging utilities occasionally need to inspect implementation
        details such as the generated globals dictionary. Exposing the raw
        function keeps those checks intact without bypassing the wrapper's
        pickling guarantees.
        """

        return self._callable

    def __call__(self, *args, **kwargs):
        """Delegate evaluation to the regenerated callable."""

        return self._callable(*args, **kwargs)

    def __getstate__(self):
        """Persist the SymPy payload so workers can rebuild the callable."""

        return dict(self._state)

    def __setstate__(self, state):
        """Restore the callable by recompiling the stored SymPy expression."""

        self._state = dict(state)
        self._callable = self._build_callable()

    def __getattr__(self, name):
        """Expose selected function attributes for compatibility."""

        if name in {"__name__", "__qualname__", "__module__"}:
            return getattr(self._callable, name)
        raise AttributeError(name)

    def _build_callable(self, *, sym_expr=None):
        """Construct and register the underlying Python callable."""

        if sym_expr is None:
            sym_expr = sp.sympify(self._state["expr_repr"], evaluate=False)
        args = tuple(sp.symbols(name) for name in self._state["arg_names"])

        if self._state["has_integral"]:
            printer = QuadPrinter({"strict": False})
            code = printer.doprint(sym_expr)
            func_name = "_generated_func"
            args_str = ", ".join(str(a) for a in args)
            src = f"def {func_name}({args_str}):\n    return {code}"
            module = ast.parse(src, mode="exec")
            compiled = compile(module, filename="<model>", mode="exec")
            env = {
                "np": np,
                "quad": quad,
                "__builtins__": {},
                "__name__": __name__,
            }
            exec(compiled, env)
            generated = env[func_name]
        else:
            generated = sp.lambdify(
                args,
                sym_expr,
                [{"__builtins__": {}}, "numpy"],
            )

        return _register_generated_callable(
            generated,
            name_hint=self._state["name_hint"],
        )


def _register_generated_callable(func, *, name_hint: str | None = None):
    """Register ``func`` on this module so it can be pickled safely.

    ``sympy.lambdify`` synthesises functions inside ephemeral modules
    whose names are meaningless once the generator finishes executing.
    Multiprocessing pools that rely on the ``spawn`` start method must
    import callables by module path, so we normalise the function name,
    attach it to :mod:`copernican_lib.model_coder` and update the
    metadata ``pickle`` expects. Using an explicit registration helper
    keeps the workflow centralised and easy to audit when new symbolic
    helpers are introduced.
    """

    module = sys.modules[__name__]
    base_name = name_hint or getattr(func, "__name__", "generated_callable")
    base_name = re.sub(r"[^0-9A-Za-z_]+", "_", base_name).strip("_")
    if not base_name:
        base_name = "generated_callable"
    while True:
        suffix = next(_GENERATED_NAME_COUNTER)
        candidate = f"_{base_name}_{suffix}"
        if not hasattr(module, candidate):
            break
    setattr(module, candidate, func)
    func.__name__ = candidate
    func.__qualname__ = candidate
    func.__module__ = module.__name__
    return func


class _ComovingDistance:
    """Picklable callable computing the comoving distance in Mpc."""

    __slots__ = ("_hz_fn",)

    def __init__(self, hz_fn):
        self._hz_fn = hz_fn

    def __call__(self, z_val, *params):
        """Integrate ``c/H(z)`` using either ``quad`` or a trapezoid grid."""

        def integrand(zp):
            return 299792.458 / self._hz_fn(zp, *params)

        if np.isscalar(z_val):
            return quad(integrand, 0.0, float(z_val), limit=100)[0]

        z_arr = np.asarray(z_val, dtype=float)
        z_flat = np.ravel(z_arr)
        if z_flat.size == 0:
            return np.asarray(z_arr, dtype=float)
        z_sorted = np.sort(z_flat)
        n_grid = max(2000, len(z_sorted) * 4)
        grid = np.linspace(0.0, z_sorted[-1], n_grid)
        integrand_vals = integrand(grid)
        cumulative = cumulative_trapezoid(integrand_vals, grid, initial=0.0)
        interp = np.interp(z_flat, grid, cumulative)
        return np.reshape(interp, np.shape(z_val))


class _LuminosityDistance:
    """Return the luminosity distance from a comoving distance helper."""

    __slots__ = ("_dm",)

    def __init__(self, dm_fn):
        self._dm = dm_fn

    def __call__(self, zv, *params):
        return (1.0 + zv) * self._dm(zv, *params)


class _AngularDiameterDistance:
    """Return the angular diameter distance from comoving distance."""

    __slots__ = ("_dm",)

    def __init__(self, dm_fn):
        self._dm = dm_fn

    def __call__(self, zv, *params):
        return self._dm(zv, *params) / (1.0 + zv)


class _VolumeAveragedDistance:
    """Compute the BAO volume-averaged distance ``D_V`` in Mpc."""

    __slots__ = ("_dm", "_hz_fn")

    def __init__(self, dm_fn, hz_fn):
        self._dm = dm_fn
        self._hz_fn = hz_fn

    def __call__(self, z_val, *params):
        dm_val = self._dm(z_val, *params)
        hz_val = self._hz_fn(z_val, *params)
        term = dm_val**2 * 299792.458 * z_val / hz_val

        if np.isscalar(z_val):
            if z_val > 0 and hz_val != 0:
                return term ** (1 / 3) if term >= 0 else np.nan
            return 0.0

        result = np.zeros_like(z_val, dtype=float)
        mask = (z_val > 0) & (hz_val != 0)
        term_arr = term[mask]
        result[mask] = np.where(
            term_arr >= 0, np.power(term_arr, 1 / 3), np.nan
        )
        return result


class _SoundHorizonFromExpression:
    """Wrap a symbolic sound-horizon function in a picklable callable."""

    __slots__ = ("_fn",)

    def __init__(self, fn):
        self._fn = fn

    def __call__(self, *params):
        return float(self._fn(*params))


class _SoundHorizonFallback:
    """Numerically integrate the baryon-photon sound horizon."""

    __slots__ = ("_hz_fn", "_omega_b_idx", "_omega_gamma_idx", "_z_rec_idx")

    def __init__(self, hz_fn, omega_b_idx, omega_gamma_idx, z_rec_idx):
        self._hz_fn = hz_fn
        self._omega_b_idx = omega_b_idx
        self._omega_gamma_idx = omega_gamma_idx
        self._z_rec_idx = z_rec_idx

    def __call__(self, *params):
        ob_val = params[self._omega_b_idx]
        og_val = params[self._omega_gamma_idx]
        zrec = params[self._z_rec_idx]

        def sound_speed(zv):
            return 299792.458 / np.sqrt(
                3.0 * (1.0 + 3.0 * ob_val / (4.0 * og_val) / (1.0 + zv))
            )

        h0_val = self._hz_fn(0.0, *params)

        def hz_with_radiation(zv):
            base = self._hz_fn(zv, *params)
            rad_sq = (h0_val**2) * og_val * (1.0 + zv) ** 4
            return np.sqrt(base**2 + rad_sq)

        def integrand(zv):
            return sound_speed(zv) / hz_with_radiation(zv)

        result, _ = quad(integrand, zrec, np.inf, limit=100)
        return result


class _DistanceModulusFromLuminosity:
    """Convert luminosity distance results to distance modulus."""

    __slots__ = ("_luminosity_fn",)

    def __init__(self, luminosity_fn):
        self._luminosity_fn = luminosity_fn

    def __call__(self, zv, *params):
        dl = self._luminosity_fn(zv, *params)
        with np.errstate(divide="ignore", invalid="ignore"):
            mu = 5.0 * np.log10(dl) + 25.0
        return np.where(np.asarray(dl) > 0, mu, np.nan)


class QuadPrinter(NumPyPrinter):
    """NumPy printer that expands ``Integral`` nodes into ``scipy``
    quad calls."""

    def _print_Integral(self, expr):
        """Translate SymPy ``Integral`` nodes into ``quad`` expressions."""
        # Currently support single-variable integrals of the form (var, a, b).
        var, a, b = expr.limits[0]
        integrand = expr.function
        var_code = self._print(var)
        a_code = self._print(a)
        b_code = self._print(b)
        integrand_code = self._print(integrand)
        return (
            f"quad(lambda {var_code}: {integrand_code}, {a_code}, "
            f"{b_code})[0]"
        )


def _latex_to_sympy_str(expr: str) -> str:
    """Convert a LaTeX-style expression to a SymPy-friendly string."""
    return latex_utils.latex_to_sympy(expr)


_SAFE_GLOBALS = {"__builtins__": {}}
_SAFE_GLOBALS.update({name: getattr(sp, name) for name in sp.__all__})


def _safe_parse_expr(expr_str: str, local_dict: dict) -> sp.Expr:
    """Safely parse ``expr_str`` into a SymPy expression.

    The parser runs with an empty ``__builtins__`` dict so that tokens like
    ``__import__`` cannot access Python's standard library. Expressions with
    double underscores are rejected outright to avoid dunder exploits.
    """

    if "__" in expr_str:
        raise ValueError(
            "Double underscores are not permitted in expressions."
        )

    return parse_expr(
        expr_str,
        local_dict,
        global_dict=_SAFE_GLOBALS,
        transformations=standard_transformations
        + (implicit_multiplication_application,),
    )


def _compile_sympy_expr(sym_expr, args, name_hint: str | None = None):
    """Return a picklable callable for ``sym_expr``.

    SymPy expressions are converted to deterministic wrappers that preserve
    the symbolic payload. When the wrapper is unpickled inside a spawned
    worker it recompiles the helper and registers it on this module
    automatically, keeping multiprocessing pools stable even when the original
    function names were assigned dynamically.
    """

    has_integral = bool(sym_expr.atoms(sp.Integral))
    arg_names = tuple(str(a) for a in args)
    expr_repr = sp.srepr(sym_expr)
    return _GeneratedCallable(
        expr_repr=expr_repr,
        arg_names=arg_names,
        has_integral=has_integral,
        name_hint=name_hint,
        sym_expr=sym_expr,
    )


def generate_callables(cache_path):
    """Create callables from the cached model and update the cache file.

    Parameters
    ----------
    cache_path : str or Path
        Path to the sanitized model YAML produced by :func:`parse_model`.

    Returns
    -------
    tuple(dict, dict)
        Dictionary of callables and the loaded YAML data.
    """
    cache_path = Path(cache_path)
    with cache_path.open("r") as f:
        model_data = yaml.safe_load(f)

    logger = logging.getLogger()

    z = sp.symbols("z")
    param_syms = [
        sp.symbols(p["python_var"]) for p in model_data["parameters"]
    ]
    local_dict = {
        p["python_var"]: sym
        for p, sym in zip(model_data["parameters"], param_syms)
    }
    local_dict["z"] = z
    # Allow YAML equations to reference the full 'sympy' prefix
    # as well as shorthand
    local_dict["sympy"] = sp

    funcs = {}
    code_dict = {}

    hz_expr_str = model_data.get("Hz_expression")
    if hz_expr_str:
        try:
            parsed_hz = _latex_to_sympy_str(hz_expr_str)
            hz_sym = _safe_parse_expr(parsed_hz, local_dict)
            used_syms = {str(s) for s in hz_sym.free_symbols if s != z}
            param_names = {p["python_var"] for p in model_data["parameters"]}
            missing = used_syms - param_names
            if missing:
                missing_str = "', '".join(missing)
                raise ValueError(
                    f"Parameter '{missing_str}' used in Hz_expression is "
                    "not defined in model parameters."
                )
            # Convert SymPy expression to a NumPy callable.
            # Any ``Integral`` terms are replaced with numerical
            # quad evaluations.

            hz_fn = _compile_sympy_expr(
                hz_sym,
                (z, *param_syms),
                name_hint="get_Hz_per_Mpc",
            )

            funcs["get_Hz_per_Mpc"] = hz_fn
            code_dict["get_Hz_per_Mpc"] = str(hz_sym)
            model_data["valid_for_distance_metrics"] = True

            dm_fn = funcs.get("get_comoving_distance_Mpc")
            if dm_fn is None:
                dm_fn = _ComovingDistance(hz_fn)
                funcs["get_comoving_distance_Mpc"] = dm_fn
                code_dict["get_comoving_distance_Mpc"] = "integral(c/H(z))"

            if "get_luminosity_distance_Mpc" not in funcs:
                funcs["get_luminosity_distance_Mpc"] = _LuminosityDistance(
                    dm_fn
                )
                code_dict["get_luminosity_distance_Mpc"] = "(1+z)*DC"

            if "get_angular_diameter_distance_Mpc" not in funcs:
                funcs["get_angular_diameter_distance_Mpc"] = (
                    _AngularDiameterDistance(dm_fn)
                )
                code_dict["get_angular_diameter_distance_Mpc"] = "DC/(1+z)"

            if "get_DV_Mpc" not in funcs:
                funcs["get_DV_Mpc"] = _VolumeAveragedDistance(dm_fn, hz_fn)
                code_dict["get_DV_Mpc"] = "((DC^2 * c*z/H)^1/3)"
            logger.info(
                "Derived distance functions from symbolic "
                "Hz_expression in model YAML."
            )

            # --- Derive sound horizon at recombination (r_s) ---
            rs_expr_str = model_data.get("rs_expression")
            param_names = {p["python_var"] for p in model_data["parameters"]}
            param_index = {
                p["python_var"]: i
                for i, p in enumerate(model_data["parameters"])
            }

            if rs_expr_str:
                try:
                    parsed_rs = _latex_to_sympy_str(rs_expr_str)
                    rs_sym = _safe_parse_expr(parsed_rs, local_dict)
                    used = {str(s) for s in rs_sym.free_symbols} - {"z"}
                    missing_rs = used - param_names
                    if missing_rs:
                        missing_str = "', '".join(missing_rs)
                        raise ValueError(
                            f"Parameter '{missing_str}' used in rs_expression "
                            "is not defined in model parameters."
                        )
                    # ``Integral`` terms here are also expanded to calls to
                    # ``quad``.

                    rs_fn_sym = _compile_sympy_expr(
                        rs_sym,
                        tuple(param_syms),
                        name_hint="get_sound_horizon_rs_Mpc",
                    )

                    funcs["get_sound_horizon_rs_Mpc"] = (
                        _SoundHorizonFromExpression(rs_fn_sym)
                    )
                    code_dict["get_sound_horizon_rs_Mpc"] = str(rs_sym)
                    model_data["valid_for_bao"] = True
                    logger.info(
                        "Derived r_s from symbolic rs_expression in model "
                        "YAML.",
                    )
                except Exception as e:
                    msg = f"Failed to parse rs_expression: {e}"
                    error_handler.report_error(msg)
                    raise ValueError(msg) from e
            elif (
                "Omega_b" in param_names
                and "Omega_gamma" in param_names
                and ("z_rec" in param_names or "z_recomb" in param_names)
                and "get_Hz_per_Mpc" in funcs
            ):
                ob_i = param_index["Omega_b"]
                og_i = param_index["Omega_gamma"]
                zr_key = "z_rec" if "z_rec" in param_names else "z_recomb"
                zr_i = param_index[zr_key]

                funcs["get_sound_horizon_rs_Mpc"] = _SoundHorizonFallback(
                    hz_fn, ob_i, og_i, zr_i
                )
                code_dict["get_sound_horizon_rs_Mpc"] = "quad(c_s/H(z))"
                model_data["valid_for_bao"] = True
                logger.info(
                    "Derived r_s using fallback integral from "
                    "Hz_expression.",
                )
            else:
                console.write(
                    "\u26A0\uFE0F  Model lacks parameters for computing "
                    "r_s. BAO scaling may be unavailable."
                )
                model_data["valid_for_bao"] = False
        except Exception as e:
            msg = f"Failed to parse Hz_expression: {e}"
            error_handler.report_error(msg)
            raise ValueError(msg) from e
    else:
        console.write(
            "\u26A0\uFE0F  Model does not define H(z). Distance-based "
            "observables such as BAO, comoving distances, and luminosity "
            "distances will be unavailable."
        )
        model_data["valid_for_distance_metrics"] = False
        model_data["valid_for_bao"] = False
    for name, expr in model_data.get("equations", {}).items():
        if not isinstance(expr, str):
            # Textual equations are preserved but not parsed into functions
            continue
        try:
            sym_expr = _safe_parse_expr(expr, local_dict)
            # Convert SymPy expression to a callable, numerically evaluating
            # ``Integral`` constructs if present.

            fn = _compile_sympy_expr(
                sym_expr,
                (z, *param_syms),
                name_hint=name,
            )

            # Quick sanity evaluation using midpoints of parameter bounds
            try:
                mid_params = tuple(
                    sum(p["bounds"]) / 2.0 for p in model_data["parameters"]
                )
                test_args = (0.5,) + mid_params
                fn(*test_args)
            except Exception as eval_e:
                error_handler.report_error(
                    f"Generated function '{name}' raised an error when "
                    f"tested: {eval_e}"
                )
            funcs[name] = fn
            code_dict[name] = str(sym_expr)
        except Exception as e:
            msg = f"Failed to parse equation '{name}': {e}"
            error_handler.report_error(msg)
            raise ValueError(msg) from e

    if (
        "distance_modulus_model" not in funcs
        and "get_luminosity_distance_Mpc" in funcs
    ):

        funcs["distance_modulus_model"] = _DistanceModulusFromLuminosity(
            funcs["get_luminosity_distance_Mpc"]
        )
        code_dict["distance_modulus_model"] = "5*log10(DL_Mpc)+25"
        logger.info("Derived distance_modulus_model from luminosity distance.")

    model_data["generated_code"] = code_dict
    with cache_path.open("w") as f:
        yaml.safe_dump(model_data, f, sort_keys=False, allow_unicode=True)

    return funcs, model_data
