# Last Updated: 2025-11-03
"""Generate a deterministic ``requirements.lock`` file for the suite.

This helper wraps :mod:`piptools` so the ``make lock`` target can decide
whether the dependency body actually changed before rewriting the
``Last Updated`` banner.  The previous workflow always replaced the
header with the current date even when the dependency graph stayed
identical.  That behaviour forced a useless diff on every lint run and
broke the expectation that ``make-lock`` is idempotent on clean
branches.  We now compare the body of the freshly compiled lockfile to
any existing copy and only advance the header timestamp when the
underlying requirements differ.
"""
from __future__ import annotations

import importlib.util
import subprocess
import sys
import tempfile
from dataclasses import dataclass
from datetime import date
from pathlib import Path
from typing import Iterable, List, Sequence

if (
    importlib.util.find_spec("piptools") is None
):  # pragma: no cover - developer guidance
    raise SystemExit(
        "pip-tools is required to regenerate requirements.lock. Install the "
        "repository's pinned version with `python -m pip install "
        "pip-tools==7.4.1`."
    )


ROOT = Path(__file__).resolve().parents[1]
REQ_IN = ROOT / "requirements.in"
LOCK_PATH = ROOT / "requirements.lock"


@dataclass(frozen=True)
class LockFilePieces:
    """Describe the pieces of a ``requirements.lock`` snapshot.

    The helper splits the file into an optional ``Last Updated`` header
    and the remaining dependency body so we can compare snapshots while
    ignoring cosmetic timestamps.  Keeping the data in a typed structure
    clarifies what ``normalise_lock`` returns and keeps the control flow
    easy to follow for future maintainers.
    """

    last_updated: str | None
    body: List[str]


def run_pip_compile(output_path: Path) -> None:
    """Invoke ``pip-compile`` with the repository's canonical flags."""

    subprocess.run(
        [
            sys.executable,
            "-m",
            "piptools",
            "compile",
            "--quiet",
            "--allow-unsafe",
            "--strip-extras",
            "--output-file",
            str(output_path),
            "requirements.in",
        ],
        cwd=ROOT,
        check=True,
    )


def normalise_header(lines: Sequence[str]) -> List[str]:
    """Stabilise ``pip-compile`` banners across Python versions."""

    python_banner = "# This file is autogenerated by pip-compile"
    target = (
        "#    pip-compile --allow-unsafe --strip-extras --output-file="
        "requirements.lock requirements.in"
    )
    result = list(lines)
    for index, line in enumerate(result):
        if line.startswith("#    pip-compile "):
            result[index] = target
            break
    for index, line in enumerate(result):
        if line.startswith(
            "# This file is autogenerated by pip-compile with Python"
        ):
            result[index] = python_banner
            break
    return result


def split_last_updated(lines: Iterable[str]) -> LockFilePieces:
    """Separate the optional ``Last Updated`` banner from the body."""

    collected = list(lines)
    if collected and collected[0].startswith("# Last Updated: "):
        return LockFilePieces(collected[0], collected[1:])
    return LockFilePieces(None, collected)


def compile_new_lock() -> LockFilePieces:
    """Generate a normalised lockfile snapshot without touching disk."""

    with tempfile.TemporaryDirectory() as tmpdir:
        tmp_lock = Path(tmpdir) / "requirements.lock"
        run_pip_compile(tmp_lock)
        normalised = normalise_header(tmp_lock.read_text().splitlines())
    return split_last_updated(normalised)


def read_existing_lock() -> LockFilePieces:
    """Return the current ``requirements.lock`` pieces, if any."""

    if not LOCK_PATH.exists():
        return LockFilePieces(None, [])
    return split_last_updated(LOCK_PATH.read_text().splitlines())


def choose_header(
    previous: LockFilePieces, current_body: Sequence[str]
) -> str:
    """Select the header to write for the upcoming lockfile update."""

    today_banner = f"# Last Updated: {date.today().isoformat()}"
    if previous.body == list(current_body) and previous.last_updated:
        return previous.last_updated
    return today_banner


def write_lock(header: str, body: Sequence[str]) -> None:
    """Persist the reconstructed lockfile with ``header`` prepended."""

    LOCK_PATH.write_text("\n".join([header, *body]) + "\n")


def main() -> None:
    """Regenerate ``requirements.lock`` without spurious diffs."""

    previous = read_existing_lock()
    current = compile_new_lock()
    header = choose_header(previous, current.body)
    write_lock(header, current.body)


if __name__ == "__main__":
    main()
