# Last Updated: 2025-11-05
"""Generate a deterministic ``requirements.lock`` file for the suite.

This helper wraps :mod:`piptools` so the ``make lock`` target can decide
whether the dependency body actually changed before rewriting the
``Last Updated`` banner.  The previous workflow always replaced the
header with the current date even when the dependency graph stayed
identical.  That behaviour forced a useless diff on every lint run and
broke the expectation that ``make-lock`` is idempotent on clean
branches.  We now compare the body of the freshly compiled lockfile to
any existing copy and only advance the header timestamp when the
underlying requirements differ.
"""
from __future__ import annotations

import argparse
import importlib.util
import subprocess
import sys
import tempfile
from dataclasses import dataclass
from datetime import date
from pathlib import Path
from typing import Iterable, List, Sequence

if (
    importlib.util.find_spec("piptools") is None
):  # pragma: no cover - developer guidance
    raise SystemExit(
        "pip-tools is required to regenerate requirements.lock. Install the "
        "repository's pinned version with `python -m pip install "
        "pip-tools==7.4.1`."
    )


ROOT = Path(__file__).resolve().parents[1]


@dataclass(frozen=True)
class LockFilePieces:
    """Describe the pieces of a ``requirements.lock`` snapshot."""

    last_updated: str | None
    body: List[str]


def ensure_inputs(root: Path) -> tuple[Path, Path]:
    """Return the ``requirements`` inputs and ensure they exist."""

    req_in = root / "requirements.in"
    lock_path = root / "requirements.lock"
    if not req_in.exists():
        raise SystemExit(
            "requirements.in is missing; run the helper from the repository "
            "root or provide --root with a valid project directory."
        )
    return req_in, lock_path


def run_pip_compile(
    root: Path, requirements_in: Path, output_path: Path
) -> None:
    """Invoke ``pip-compile`` with the repository's canonical flags."""

    subprocess.run(
        [
            sys.executable,
            "-m",
            "piptools",
            "compile",
            "--quiet",
            "--allow-unsafe",
            "--strip-extras",
            "--output-file",
            str(output_path),
            requirements_in.name,
        ],
        cwd=root,
        check=True,
    )


def normalise_header(lines: Sequence[str]) -> List[str]:
    """Stabilise ``pip-compile`` banners across Python versions."""

    python_banner = "# This file is autogenerated by pip-compile"
    target = (
        "#    pip-compile --allow-unsafe --strip-extras --output-file="
        "requirements.lock requirements.in"
    )
    result = list(lines)
    for index, line in enumerate(result):
        if line.startswith("#    pip-compile "):
            result[index] = target
            break
    for index, line in enumerate(result):
        if line.startswith(
            "# This file is autogenerated by pip-compile with Python"
        ):
            result[index] = python_banner
            break
    return result


def split_last_updated(lines: Iterable[str]) -> LockFilePieces:
    """Separate the optional ``Last Updated`` banner from the body."""

    collected = list(lines)
    if collected and collected[0].startswith("# Last Updated: "):
        return LockFilePieces(collected[0], collected[1:])
    return LockFilePieces(None, collected)


def compile_new_lock(root: Path, requirements_in: Path) -> LockFilePieces:
    """Generate a normalised lockfile snapshot without touching disk."""

    with tempfile.TemporaryDirectory() as tmpdir:
        tmp_lock = Path(tmpdir) / "requirements.lock"
        run_pip_compile(root, requirements_in, tmp_lock)
        normalised = normalise_header(tmp_lock.read_text().splitlines())
    return split_last_updated(normalised)


def read_existing_lock(lock_path: Path) -> LockFilePieces:
    """Return the current ``requirements.lock`` pieces, if any."""

    if not lock_path.exists():
        return LockFilePieces(None, [])
    return split_last_updated(lock_path.read_text().splitlines())


def choose_header(
    previous: LockFilePieces,
    current_body: Sequence[str],
    today: date,
) -> str:
    """Select the header to write for the upcoming lockfile update."""

    today_banner = f"# Last Updated: {today.isoformat()}"
    if previous.body == list(current_body) and previous.last_updated:
        return previous.last_updated
    return today_banner


def write_lock(lock_path: Path, header: str, body: Sequence[str]) -> None:
    """Persist the reconstructed lockfile with ``header`` prepended."""

    lock_path.write_text("\n".join([header, *body]) + "\n", encoding="utf-8")


def update_lockfile(
    root: Path,
    *,
    today: date | None = None,
) -> bool:
    """Refresh ``requirements.lock`` and return ``True`` when it changed."""

    requirements_in, lock_path = ensure_inputs(root)
    previous = read_existing_lock(lock_path)
    compiled = compile_new_lock(root, requirements_in)
    banner = choose_header(previous, compiled.body, today or date.today())
    if previous.last_updated == banner and previous.body == compiled.body:
        return False
    write_lock(lock_path, banner, compiled.body)
    return True


def parse_args() -> argparse.Namespace:
    """Return command-line arguments for the helper."""

    parser = argparse.ArgumentParser(
        description=(
            "Regenerate requirements.lock while keeping the Last Updated "
            "banner stable when the dependency body is unchanged."
        )
    )
    parser.add_argument(
        "--root",
        type=Path,
        default=ROOT,
        help=(
            "Project root containing requirements.in and requirements.lock. "
            "Defaults to the repository root inferred from this script."
        ),
    )
    return parser.parse_args()


def main() -> None:
    """Entry-point for the command-line interface."""

    args = parse_args()
    changed = update_lockfile(args.root)
    if changed:
        print("requirements.lock updated", file=sys.stdout)
    else:
        print("requirements.lock already up to date", file=sys.stdout)


if __name__ == "__main__":
    main()
