# Last Updated: 2025-10-30
name: Lint

on:
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up virtual environment
        run: python -m venv .venv

      - name: Install dependencies
        run: |
          .venv/bin/python -m pip install pip==24.2
          .venv/bin/python -m pip install -r requirements.lock
          .venv/bin/python -m pip install --no-deps .
          .venv/bin/python -m pip install pre-commit
          .venv/bin/python -m pip install pip-tools==7.4.1

      - name: Run pre-commit
        run: .venv/bin/pre-commit run --all-files
